### ISSUE TITLE
markdown disabled in westworld2.com

### ISSUE THREAD

**Issue by atiq-cs** [russellballestrini/remarkbox-westworld#1]
Is markdown preview disabled in https://westworld2.com ?

**Comment by russellballestrini** [comment]
Seems broken actually. I should look into that, likely a CSRF issue. Thank for letting me know & I'll get back to you.

BTW, are you interested in learning more about the Remarkbox code base?

**Comment by atiq-cs** [comment]
> are you interested in learning more about the Remarkbox code base?

Is it better than `utterances`?

**Comment by russellballestrini** [comment]
Gosh I hope so, using github issues as an API for comments on web page seems brittle.

**Comment by russellballestrini** [comment]
Yup, it was defect in my CSRF logic. Was an issue also affecting all Remarkbox users too! Thanks for the bug report!

**Comment by russellballestrini** [comment]
Fixed in production!
